### ISSUE TITLE
Release 1.0.0?

### ISSUE THREAD

**Issue by vlsi** [SimY4/coregex#32]
It looks like there are multiple plugins for various test libraries.
What do you think of releasing 1.0.0?

I guess it would improve the perception from the consumers point of view.

**Comment by SimY4** [comment]
Hey. Sorry for not being transparent about this library. I'm currently seeking for good solutions a few things that I'd personally use in my regexes.

To keep it transparent I just created a [Milestone for v1.0](https://github.com/SimY4/coregex/milestone/1) and added those items to it. If you have something you would want this library to support, let's add it there and find solutions for it.

**Comment by vlsi** [comment]
I think the current state qualifies for 1.0.0, while the ideas you mention can go under 1.1.0, and so on

**Comment by SimY4** [comment]
@vlsi Fair enough. I'll carve one today

**Comment by SimY4** [comment]
Should be in maven central within the next couple of hours.
